### ISSUE TITLE
Linux中国停运不是终点，麟悦（Linuxjoy.com）今日上线

### ISSUE THREAD

**Issue by modiqi** [Linux-CN/archive#1]
【一鲸落，万物生】Linux中国停运不是终点，麟悦（[Linuxjoy.com](url)）今日上线，我们已最大限度的保留备份了全部内容可以在线浏览，未来将会尝试提供Linux信息推送服务。

<img width="1073" alt="Screenshot2024-02-19 17 34 48" src="https://github.com/Linux-CN/archive/assets/130886204/6a83d4e4-229b-416f-b0b6-d857df59af91">

———

开这篇 issues 是因为前几天看到 Linux.cn 的存档站 403 ，考虑到如果是同一台服务器或者子域名的话，未来也不清楚老王叔会如何给老站一个好归宿，以防万一可能的导致数据丢失和不存在。

我们考虑了下就启用了 Linux joy 这个备用的品牌词来做为Linux中国的数据转接存档，花了两三天做数据转换到了 WordPress 站点，这也算是给到一个新的存档。

未来如果我们有余力或者能够有足够的闲余资金，将会尝试接过大旗来做继续做这项 Linux 中国的推广和全球新闻推送服务。

**Comment by bestony** [comment]
啊，哪里403 啦？我去看看

**Comment by bestony** [comment]
可能是因为我中间在调试 CDN 啥的导致的。

**Comment by bestony** [comment]
我看看配置去。。。

**Comment by bestony** [comment]
已经恢复了～可以看看～ @modiqi

**Comment by oneadm** [comment]
Yet another archive

https://www.4uref.com/zh/linux-cn/

**Comment by birdofprey** [comment]
感谢凤凰涅槃！！！记下了，以后就关注这个站了

**Comment by you-hengh** [comment]
你好 @modiqi , 网站当前不可访问, 请问什么时候可以恢复呢?

![2024-03-19_16-03-41](https://github.com/Linux-CN/archive/assets/34816426/83706aff-8ccb-40c5-924f-f8a49b125513)

当前时间: 2024年3月19日16点08分

**Comment by bestony** [comment]
> 你好 @modiqi , 网站当前不可访问, 请问什么时候可以恢复呢?
> 
> ![2024-03-19_16-03-41](https://private-user-images.githubusercontent.com/34816426/313971745-83706aff-8ccb-40c5-924f-f8a49b125513.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mzc0NDAsIm5iZiI6MTcxMDgzNzE0MCwicGF0aCI6Ii8zNDgxNjQyNi8zMTM5NzE3NDUtODM3MDZhZmYtOGNjYi00MGM1LTkyNGYtZjhhNDliMTI1NTEzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA4MzIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NzM5MDUxYjY0NmEzYzU4ZjY2Njg5NjM4MjE0YjFjMTZmOGY5NzQyNGMwZDg3ZDk4N2RmN2E2NDNlYjFjZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xhhWTkgmUnKtay22A2t4axEzoJwOZ_9t2-N69RIJUm0)
> 
> 当前时间: 2024年3月19日16点08分

🤣 好家伙。。。
